# Broker VM
[azure_broker]
broker-vm ansible_host=13.78.x.x

# Consumer VM
[azure_consumer]
consumer-vm ansible_host=20.12.x.x

# Azure VM
[azure_vms:children]
azure_broker
azure_consumer

[azure_vms:vars]
ansible_user=palja
ansible_python_interpreter=/usr/bin/python3