[all:vars]
# SSH 접속 사용자 (AWS Ubuntu AMI 기준)
ansible_user=ubuntu

# 홈 디렉토리의 .ssh 폴더 내 키 페어 참조
ansible_ssh_private_key_file=~/.ssh/key.pem

# 처음 접속 시 보안 확인(Fingerprint) 절차 자동 통과
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[masters]
# 마스터 노드 Private IP를 입력하세요
10.0.1.10

[workers]
# 워커 노드들의 Private IP를 입력하세요
10.0.2.10
10.0.2.11

[k8s_cluster:children]
masters
workers