FROM confluentinc/cp-kafka-connect:7.5.0

USER root
RUN microdnf update && microdnf install -y unzip && microdnf clean all

# ZIP 파일 복사
# confluentinc-kafka-connect-azure-blob-storage-2.1.2
# confluentinc-kafka-connect-s3-10.5.0
COPY azure-part1.zip azure-part2.zip s3.zip /tmp/

# 플러그인 루트 폴더 생성
RUN mkdir -p /usr/share/confluent-hub-components/azure-blob/lib && \
    mkdir -p /usr/share/confluent-hub-components/s3/lib

# 압축 해제 및 파일 정리
# Azure Part 1 & 2
RUN unzip -j /tmp/azure-part1.zip "*/lib/*.jar" -d /usr/share/confluent-hub-components/azure-blob/lib/ && \
    unzip -j /tmp/azure-part2.zip "*/lib/*.jar" -d /usr/share/confluent-hub-components/azure-blob/lib/ && \
    unzip -j /tmp/azure-part1.zip "*/manifest.json" -d /usr/share/confluent-hub-components/azure-blob/

# S3
RUN unzip -j /tmp/s3.zip "*/lib/*.jar" -d /usr/share/confluent-hub-components/s3/lib/ && \
    unzip -j /tmp/s3.zip "*/manifest.json" -d /usr/share/confluent-hub-components/s3/

# 권한 부여 및 임시 파일 삭제
RUN chown -R appuser:appuser /usr/share/confluent-hub-components && \
    rm /tmp/*.zip

USER appuser

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

CMD ["/etc/confluent/docker/run"]