apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-login
  namespace: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-login
  template:
    metadata:
      labels:
        app: backend-login
    spec:
      tolerations:
        - key: nodetype
          operator: Equal
          value: user
          effect: NoSchedule
      nodeSelector:
        role: user-worker
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: backend-login
                topologyKey: kubernetes.io/hostname
      containers:
        - name: backend-login
          image: wooyeol43/login-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: db-secret
                optional: true
            - configMapRef:
                name: web-platform-backend-config
            - secretRef:
                name: web-platform-backend-secret
          env:
            - name: APP_TARGET
              value: "login"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
