apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-operator
  namespace: operator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-operator
  template:
    metadata:
      labels:
        app: backend-operator
    spec:
      tolerations:
        - key: nodetype
          operator: Equal
          value: operator
          effect: NoSchedule
      nodeSelector:
        role: operator-worker
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: backend-operator
                topologyKey: kubernetes.io/hostname
      containers:
        - name: backend-operator
          image: kimsewon/operator-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: web-platform-backend-config
            - secretRef:
                name: web-platform-backend-secret
          env:
            - name: APP_TARGET
              value: "operator"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
