---
- name: Install K3s worker node
  shell: |
    ROLE_TYPE=$([[ "{{ inventory_hostname }}" =~ "op" ]] && echo "operator" || echo "user")

    curl -sfL https://get.k3s.io | K3S_URL=https://{{ nlb_dns }}:6443 \
    K3S_TOKEN="{{ k3s_shared_token }}" sh -s - agent \
    --node-taint nodetype=${ROLE_TYPE}:NoSchedule \
    --node-label role=${ROLE_TYPE}-worker
  args:
    creates: /usr/local/bin/k3s
