apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  namespace: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      tolerations:
        - key: nodetype
          operator: Equal
          value: user
          effect: NoSchedule
      nodeSelector:
        role: user-worker
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: backend-user
                topologyKey: kubernetes.io/hostname
      containers:
        - name: backend-user
          image: kimsewon/user-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: web-platform-backend-config
            - secretRef:
                name: web-platform-backend-secret
          env:
            - name: APP_TARGET
              value: "user"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://app.palja.click,http://admin.palja.click"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
